
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhruv
 */
public class MovieDescription extends javax.swing.JFrame {

  Connection conn = null;
  Statement stmt = null;
  ResultSet rs = null;
  
    public MovieDescription()
    {
        initComponents();
         
    }
    String pass="";
    public MovieDescription(String x) throws SQLException {
        initComponents();
        conn = databaseConnection.connection();
        stmt = conn.createStatement();
        String sql="Select * from moviename";
        rs=stmt.executeQuery(sql);
        String name="";       
        String duration="";
        String rating="";
        String certification="";
        String genre="";
                
      
        while(rs.next())
        {
            if(x.equals(rs.getString("Name")))
            {
                name=rs.getString("Name");              
                duration=rs.getString("Duration");
                rating=rs.getString("Rating");
                genre=rs.getString("Genre");
                certification=rs.getString("Certification");
            }
        }
        pass=x;
        show_name.setText(name);
        show_duration.setText(duration);
        show_rating.setText(rating);
        show_genre.setText(genre);
        show_certification.setText(certification);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        show_duration = new javax.swing.JLabel();
        show_rating = new javax.swing.JLabel();
        show_genre = new javax.swing.JLabel();
        show_certification = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        show_name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(null);

        show_duration.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        show_duration.setForeground(new java.awt.Color(51, 51, 51));
        show_duration.setText("show_duration");
        jPanel1.add(show_duration);
        show_duration.setBounds(240, 170, 226, 73);

        show_rating.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        show_rating.setForeground(new java.awt.Color(51, 51, 51));
        show_rating.setText("show_rating");
        jPanel1.add(show_rating);
        show_rating.setBounds(240, 330, 241, 85);

        show_genre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        show_genre.setForeground(new java.awt.Color(51, 51, 51));
        show_genre.setText("show_genre");
        jPanel1.add(show_genre);
        show_genre.setBounds(240, 250, 241, 68);

        show_certification.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        show_certification.setForeground(new java.awt.Color(51, 51, 51));
        show_certification.setText("show_certification");
        jPanel1.add(show_certification);
        show_certification.setBounds(240, 400, 219, 107);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 510, 190, 29);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Movie Duration:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 170, 152, 73);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Movie Genre:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 260, 152, 52);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Movie Rating:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 360, 183, 21);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Movie Certification:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 430, 183, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\popcorn.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(430, 130, 380, 430);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        show_name.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        show_name.setForeground(new java.awt.Color(255, 255, 255));
        show_name.setText("show_name");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\back2.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(show_name, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_name, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 810, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
          // TODO add your handling code here:
          
          // this.setVisible(false);
          ShowTiming obj3=new ShowTiming();
          ShowTimingIT obj4 = new ShowTimingIT();
          ShowTimingRambo obj5 = new ShowTimingRambo();
          if(pass.equals("Joker (2019)"))
          {
              this.setVisible(false);
              obj3.setVisible(true);
          }
          
          else if(pass.equals("IT Chapter Two"))
          {
              this.setVisible(false);
              obj4.setVisible(true);
          }
          
          else if(pass.equals("Rambo: Last Blood"))
          {
              this.setVisible(false);
              obj5.setVisible(true);
          }
          
          
      } catch (SQLException ex) {
          Logger.getLogger(MovieDescription.class.getName()).log(Level.SEVERE, null, ex);
      }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {
          // TODO add your handling code here:
          NowShowing obj1=new NowShowing();
          this.setVisible(false);
          obj1.setVisible(true);
      } catch (SQLException ex) {
          Logger.getLogger(MovieDescription.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel show_certification;
    private javax.swing.JLabel show_duration;
    private javax.swing.JLabel show_genre;
    private javax.swing.JLabel show_name;
    private javax.swing.JLabel show_rating;
    // End of variables declaration//GEN-END:variables

  /*  private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
}
