
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhruv
 */
public class NowShowing extends javax.swing.JFrame {

    /**
     * Creates new form NowShowing
     */
    Connection conn;
    Statement stmt;
    ResultSet rs;
    public NowShowing() throws SQLException {
        initComponents();
        conn = databaseConnection.connection();
        stmt = conn.createStatement();
         String sql="Select * from userinfo";
        rs=stmt.executeQuery(sql);
        String name="";
        while(rs.next()){
        name=rs.getString("name");}
        name=name.toUpperCase();
        name=name+"!";
        jLabel3.setText(name);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        joker = new javax.swing.JButton();
        ITChapterTwo = new javax.swing.JButton();
        Rambo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2041, 978));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(825, 790));
        jPanel1.setLayout(null);

        joker.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\jokerfinal.jpg")); // NOI18N
        joker.setText("jButton1");
        joker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jokerActionPerformed(evt);
            }
        });
        jPanel1.add(joker);
        joker.setBounds(30, 210, 170, 180);

        ITChapterTwo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\ITFinal.jpg")); // NOI18N
        ITChapterTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITChapterTwoActionPerformed(evt);
            }
        });
        jPanel1.add(ITChapterTwo);
        ITChapterTwo.setBounds(270, 210, 180, 180);

        Rambo.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\rambofinal.jpg")); // NOI18N
        Rambo.setText("jButton2");
        Rambo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RamboActionPerformed(evt);
            }
        });
        jPanel1.add(Rambo);
        Rambo.setBounds(510, 210, 170, 180);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME,");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 130);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("COMING SOON:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 420, 310, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("NOW SHOWING:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 150, 310, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\black widow.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 470, 150, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\dabang3.jpg")); // NOI18N
        jLabel7.setText("jLabel4");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 470, 150, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RamboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RamboActionPerformed
        // TODO add your handling code here:
        try{
            this.setVisible(false);
            new MovieDescription("Rambo: Last Blood").setVisible(true);
        }catch(SQLException ex){
            Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_RamboActionPerformed

    private void ITChapterTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITChapterTwoActionPerformed
        // TODO add your handling code here:
        try{
            this.setVisible(false);
            new MovieDescription("IT Chapter Two").setVisible(true);
        }catch(SQLException ex){
            Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_ITChapterTwoActionPerformed

    private void jokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jokerActionPerformed
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            new MovieDescription("Joker (2019)").setVisible(true);;

        } catch (SQLException ex) {
            Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jokerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NowShowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new NowShowing().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(NowShowing.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ITChapterTwo;
    private javax.swing.JButton Rambo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton joker;
    // End of variables declaration//GEN-END:variables
}
