
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhruv
 */
public class ShowTimingIT extends javax.swing.JFrame {
    
         Connection conn;
        Statement stmt;
        ResultSet rs;
        String[] timings=new String[100];
        String[] theatres=new String[100];

    /**
     * Creates new form ShowTimingIT
     */
    public ShowTimingIT() throws SQLException {
        initComponents();   
         
        conn = databaseConnection.connection();
        stmt = conn.createStatement();
        String sql="Select * from Theatres";
        rs=stmt.executeQuery(sql);
        String theatre="",timing="";
        int i=0;
        
        while(rs.next())
            {
               
                if("IT Chapter Two".equals(rs.getString("MovieName")))
                {
                
                   theatre = rs.getString("TheatreName");
                   timing=rs.getString("ShowTiming");
                   timings[i]=timing;
                   theatres[i]=theatre;
                   i++;
                   System.out.println(theatre);
                }

            }
        theatre1.setText(theatres[3]);
        
        timing1.setText(timings[2]);
        
        theatre2.setText(theatres[0]);
        timing2.setText(timings[0]);
        timing3.setText(timings[1]);
        
        theatre3.setText(theatres[2]);
        timing4.setText(timings[3]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        theatre1 = new javax.swing.JLabel();
        timing1 = new javax.swing.JButton();
        theatre2 = new javax.swing.JLabel();
        timing2 = new javax.swing.JButton();
        timing3 = new javax.swing.JButton();
        theatre3 = new javax.swing.JLabel();
        timing4 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        theatre1.setBackground(new java.awt.Color(51, 51, 51));
        theatre1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        theatre1.setForeground(new java.awt.Color(255, 51, 51));
        theatre1.setText("jLabel2");
        jPanel1.add(theatre1);
        theatre1.setBounds(30, 200, 265, 33);

        timing1.setBackground(new java.awt.Color(255, 51, 51));
        timing1.setForeground(new java.awt.Color(255, 255, 255));
        timing1.setText("jButton1");
        timing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timing1ActionPerformed(evt);
            }
        });
        jPanel1.add(timing1);
        timing1.setBounds(30, 240, 93, 29);

        theatre2.setBackground(new java.awt.Color(0, 0, 0));
        theatre2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        theatre2.setForeground(new java.awt.Color(255, 51, 51));
        theatre2.setText("jLabel2");
        jPanel1.add(theatre2);
        theatre2.setBounds(30, 290, 224, 34);

        timing2.setBackground(new java.awt.Color(255, 51, 51));
        timing2.setForeground(new java.awt.Color(255, 255, 255));
        timing2.setText("jButton1");
        timing2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timing2ActionPerformed(evt);
            }
        });
        jPanel1.add(timing2);
        timing2.setBounds(30, 340, 93, 29);

        timing3.setBackground(new java.awt.Color(255, 51, 51));
        timing3.setForeground(new java.awt.Color(255, 255, 255));
        timing3.setText("jButton1");
        timing3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timing3ActionPerformed(evt);
            }
        });
        jPanel1.add(timing3);
        timing3.setBounds(140, 340, 93, 29);

        theatre3.setBackground(new java.awt.Color(51, 51, 51));
        theatre3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        theatre3.setForeground(new java.awt.Color(255, 51, 51));
        theatre3.setText("jLabel2");
        jPanel1.add(theatre3);
        theatre3.setBounds(30, 390, 173, 29);

        timing4.setBackground(new java.awt.Color(255, 51, 51));
        timing4.setForeground(new java.awt.Color(255, 255, 255));
        timing4.setText("jButton1");
        timing4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timing4ActionPerformed(evt);
            }
        });
        jPanel1.add(timing4);
        timing4.setBounds(30, 420, 93, 29);

        panel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("IT ");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\ITFinal.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panel1);
        panel1.setBounds(0, 0, 990, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhruv\\OneDrive\\Desktop\\Project icons\\movietiming.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 140, 410, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timing2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timing2ActionPerformed
             try {
                 // TODO add your handling code here:
                 SeatingArrangement1 obj1=new SeatingArrangement1("IT Chapter Two",timings[0],theatres[0]);
                 this.setVisible(false);
                 obj1.setVisible(true);
             } catch (SQLException ex) {
                 Logger.getLogger(ShowTimingIT.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_timing2ActionPerformed

    private void timing4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timing4ActionPerformed
             try {
                 // TODO add your handling code here:
                 SeatingArrangement1 obj1=new SeatingArrangement1("IT Chapter Two",timings[3],theatres[2]);
                 this.setVisible(false);
                 obj1.setVisible(true);
             } catch (SQLException ex) {
                 Logger.getLogger(ShowTimingIT.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_timing4ActionPerformed

    private void timing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timing1ActionPerformed
             try {
                 // TODO add your handling code here:
                 // TODO add your handling code here:
                 SeatingArrangement1 obj1=new SeatingArrangement1("IT Chapter Two",timings[2],theatres[3]);
                 this.setVisible(false);
                 obj1.setVisible(true);
             } catch (SQLException ex) {
                 Logger.getLogger(ShowTimingIT.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_timing1ActionPerformed

    private void timing3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timing3ActionPerformed
             try {
                 // TODO add your handling code here:
                 // TODO add your handling code here:
                 SeatingArrangement1 obj1=new SeatingArrangement1("IT Chapter Two",timings[1],theatres[0]);
                 this.setVisible(false);
                 obj1.setVisible(true);
             } catch (SQLException ex) {
                 Logger.getLogger(ShowTimingIT.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_timing3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try {
                 // TODO add your handling code here:
                 NowShowing obj1=new NowShowing();
                 this.setVisible(false);
                 obj1.setVisible(true);
             } catch (SQLException ex) {
                 Logger.getLogger(ShowTimingIT.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowTimingIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowTimingIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowTimingIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowTimingIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowTimingIT().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ShowTimingIT.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    private javax.swing.JLabel theatre1;
    private javax.swing.JLabel theatre2;
    private javax.swing.JLabel theatre3;
    private javax.swing.JButton timing1;
    private javax.swing.JButton timing2;
    private javax.swing.JButton timing3;
    private javax.swing.JButton timing4;
    // End of variables declaration//GEN-END:variables
}
